### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by jonyking** [ujamii/openimmo#6] opened 2021-01-13 10:04 UTC
Hello,

when I try to use the example code it gives me a error message.

Code:

```
$xmlString = file_get_contents('./example/foobar.xml');
/* @var $openImmo \Ujamii\OpenImmo\API\Openimmo */
$openImmo = $this->serializer->deserialize($xmlString, \Ujamii\OpenImmo\API\Openimmo::class, 'xml');

/* @var $anbieter \Ujamii\OpenImmo\API\Anbieter */
foreach ($openImmo->getAnbieter() as $anbieter) {
    /* @var $immobilie \Ujamii\OpenImmo\API\Immobilie */
    foreach ($anbieter->getImmobilie() as $immobilie) {
        echo PHP_EOL . vsprintf('%s %s, %s %s', [
                $immobilie->getGeo()->getStrasse(),
                $immobilie->getGeo()->getHausnummer(),
                $immobilie->getGeo()->getPlz(),
                $immobilie->getGeo()->getOrt(),
            ]);
    }
}
```

Error:

`Fatal error: Uncaught Error: Using $this when not in object context in /var/www/vhosts/yfain.de/httpdocs/index.php:11 Stack trace: #0 {main} thrown in`

That should be fixed at the example.

**Comment by mgrundkoetter** [comment] 2021-01-13 10:11
Duplicate of #5

**Closed by mgrundkoetter** 2021-01-13 10:11 UTC
